# Generated by Django 4.1.4 on 2023-09-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=128)),
                ('apellido_materno', models.CharField(max_length=128)),
                ('saldo_contable', models.IntegerField(default=0)),
                ('saldo_cta_corriente', models.IntegerField(default=0)),
                ('saldo_linea_credito', models.IntegerField(default=0)),
                ('total_cargos', models.IntegerField(default=0)),
                ('total_abonos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
